syn on
set nu
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif
endif
set incsearch
set hlsearch
set wrapscan
set noic
set nocompatible
filetype plugin indent on


" Reselect visual block after indent/outdent
" http://vimbits.com/bits/20
vnoremap < <gv
vnoremap > >gv

au BufRead,BufNewFile Vagrantfile set filetype=ruby
