if has("syntax")
  syn on
end
set t_Co=256

set nu
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif
endif
set incsearch
set hlsearch
set wrapscan
set noic
set nocompatible
filetype plugin indent on

set backupdir=~/.vim/tmp
set directory=~/.vim/tmp

" Reselect visual block after indent/outdent
" http://vimbits.com/bits/20
vnoremap < <gv
vnoremap > >gv

" Sometimes the terminal isn't setup sanely, fix backspace.
imap <C-?> <C-h>

au BufRead,BufNewFile Vagrantfile set filetype=ruby
