(deftheme SexyPonies
  "Created 2011-10-08.")

(custom-theme-set-faces
 'SexyPonies
 '(cursor ((t (:background "#9f9f9f"))))
 '(minibuffer-prompt ((t (:foreground "#347fff"))))
 '(highlight ((t (:background "#2a2a2a"))))
 '(region ((t (:background "#0F224C"))))
 '(font-lock-comment-face ((t (:foreground "#969896"))))
 '(font-lock-builtin-face ((t (:foreground "#347fff"))))
 '(font-lock-constant-face ((t (:foreground "#B934FF"))))
 '(font-lock-string-face ((t (:foreground "#FF6F34"))))
 '(font-lock-type-face ((t (:foreground "#ff3454"))))
 '(font-lock-variable-name-face ((t (:foreground "#b9ff34"))))
 '(font-lock-function-name-face ((t (:foreground "#347fff"))))
 '(font-lock-keyword-face ((t (:foreground "#9575ff"))))
 '(link ((t (:foreground "#7561F6" :underline t))))
 '(header-line ((t (:inherit mode-line :background "#2a2a2a" :foreground "grey90" :box nil))))
 '(font-lock-warning-face ((t (:slant italic :foreground "#ff0000" :underline t :weight bold))))
 '(mode-line ((t (:background "#2a2a2a" :foreground "#dedede" :box (:line-width -1 :style released-button)))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "#c397d8" :style released-button)))))
 '(isearch ((t (:background "#F67561" :foreground "brown4"))))

 ;; Org-mode
 '(org-hide ((t (:foreground "#2e3436"))))
 '(org-level-1 ((t (:bold t :foreground "#3e88ba" :height 1.5))))
 '(org-level-2 ((t (:bold nil :foreground "#f0f3b4" :height 1.2))))
 '(org-level-3 ((t (:bold t :foreground "#e5642a" :height 1.0))))
 '(org-level-4 ((t (:bold nil :foreground "#f4433a" :height 1.0))))
 '(org-level-5 ((t (:bold nil :foreground "#603086" :height 1.0))))
 '(org-level-6 ((t (:bold nil :foreground "#5eba54" :height 1.0))))
 '(org-date ((t (:underline t :foreground "#5288a0"))))
 '(org-footnote  ((t (:underline t :foreground "magenta3"))))
 '(org-link ((t (:foreground "skyblue2" :background "#2e3436"))))
 '(org-special-keyword ((t (:foreground "brown"))))
 '(org-verbatim ((t (:foreground "#eeeeec" :underline t :slant italic))))
 '(org-block-begin-line ((t (:foreground "#65a1ad"))))
 '(org-block-end-line ((t (:foreground "#65a1ad"))))
 '(org-block ((t (:foreground "#6e7d9d"))))
 '(org-quote ((t (:inherit org-block :slant italic))))
 '(org-verse ((t (:inherit org-block :slant italic))))
 '(org-todo ((t (:bold t :foreground "Red"))))
 '(org-done ((t (:bold t :foreground "ForestGreen"))))
 '(org-agenda-structure ((t (:weight bold :foreground "tomato"))))
 '(org-agenda-date ((t (:foreground "#6ac214"))))
 '(org-agenda-date-weekend ((t (:weight normal :foreground "dodger blue"))))
 '(org-agenda-date-today ((t (:weight bold :foreground "#edd400"))))
 '(tool-tips ((t (:inherit 'variable-pitch :foreground "black" :background "lightyellow"))))
 '(tooltip ((t (:inherit 'variable-pitch :foreground "black" :background "lightyellow"))))
 '(ac-selection-face ((t (:background "#8C2DE0"))))


 '(default ((t (:inherit nil :stipple nil :background "black" :foreground "#dedede" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 150 :width normal :foundry "unknown" :family "DejaVu Sans Mono")))))

(provide-theme 'SexyPonies)
